title: "糖友之家"
description: "这是糖友之家博客，也是shop.tangyou.space的配套博客，也是个人记录健康日志的地方"
url: "https://blog.tangyou.space" # 替换为你的用户名
theme: jekyll-theme-Cayman
sitemap: true
include:
  - .html
  - .md
  - docs
plugins:
  - jekyll-sitemap
  - jekyll-feed

gitalk:
  enable: true
  clientID: 'Ov23liJ0om493oC1evt5'
  clientSecret: '831be8e368fb599cc7c277bf331ad2efda9b6d36'
  repo: 'https://jingchunzhang.github.io/'
  owner: 'jingchunzhang'
  admin: ['jingchunzhang']
  distractionFreeMode: true
