title: "糖友空间 Tangyou Space"
description: "广州一诺张杨人工智能科技有限责任公司｜糖尿病知识与电子资料｜Shopify/WordPress 应用开发、广告联盟与 SEO 服务"
url: "https://www.tangyou.space"
baseurl: ""
theme: jekyll-theme-Cayman
include:
  - .html
  - .md
  - docs
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - _ai
  - _website
  - _gemini
  - _site
  - ref.txt

